# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=mos-expand-memops -verify-machineinstrs -o - %s | FileCheck %s

# Test that memcpy uses reverse loop with TYA/BNE pattern (handles size 0-255)
---
name: memcpy_basic
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc2, $rc3, $rc4, $rc5, $rc6, $rc7
    ; CHECK-LABEL: name: memcpy_basic
    ; CHECK: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $rc2, $rc3, $rc4, $rc5, $rc6, $rc7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $y = COPY $rc6
    ; CHECK-NEXT: CmpBrZero %bb.2, undef $z, 1, $rc6, implicit-def $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $y, $rs2, $rs3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: DEY_Implied
    ; CHECK-NEXT: $a = LDIndirIdx $rs3, $y
    ; CHECK-NEXT: STIndirIdx $a, $rs2, $y
    ; CHECK-NEXT: TYA_Implied implicit-def $z
    ; CHECK-NEXT: BR %bb.1, $z, 0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: RTS
    MemCpy $rs2, $rs3, $rc6, $rc7, implicit-def $a, implicit-def $x, implicit-def $y, implicit-def $c, implicit-def $n, implicit-def $v, implicit-def $z
    RTS
...

# Test that memset uses reverse loop with TYA/BNE pattern (handles size 0-255)
---
name: memset_basic
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc2, $rc3, $rc4, $rc6, $rc7
    ; CHECK-LABEL: name: memset_basic
    ; CHECK: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $rc2, $rc3, $rc4, $rc6, $rc7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $y = COPY $rc6
    ; CHECK-NEXT: CmpBrZero %bb.2, undef $z, 1, $rc6, implicit-def $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $y, $rs2, $rc4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: DEY_Implied
    ; CHECK-NEXT: $a = COPY $rc4
    ; CHECK-NEXT: STIndirIdx $a, $rs2, $y
    ; CHECK-NEXT: TYA_Implied implicit-def $z
    ; CHECK-NEXT: BR %bb.1, $z, 0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: RTS
    MemSet $rs2, $rc4, $rc6, $rc7, implicit-def $a, implicit-def $x, implicit-def $y, implicit-def $c, implicit-def $n, implicit-def $v, implicit-def $z
    RTS
...

# Test that memmove uses forward loop (preserves overlapping semantics)
---
name: memmove_basic
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc2, $rc3, $rc4, $rc5, $rc6, $rc7
    ; CHECK-LABEL: name: memmove_basic
    ; CHECK: successors: %bb.1(0x80000000)
    ; CHECK-NEXT: liveins: $rc2, $rc3, $rc4, $rc5, $rc6, $rc7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $y = LDImm 0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $y, $rs2, $rc6, $rs3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = LDIndirIdx $rs3, $y
    ; CHECK-NEXT: STIndirIdx $a, $rs2, $y
    ; CHECK-NEXT: INY_Implied
    ; CHECK-NEXT: CmpBrImag8 %bb.1, undef $z, 0, $y, $rc6, implicit-def $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: RTS
    MemMove $rs2, $rs3, $rc6, $rc7, implicit-def $a, implicit-def $x, implicit-def $y, implicit-def $c, implicit-def $n, implicit-def $v, implicit-def $z
    RTS
...

# Test that memmove reverse uses reverse loop with TYA/BNE (for overlapping dst > src)
---
name: memmove_reverse_basic
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc2, $rc3, $rc4, $rc5, $rc6, $rc7
    ; CHECK-LABEL: name: memmove_reverse_basic
    ; CHECK: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $rc2, $rc3, $rc4, $rc5, $rc6, $rc7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $y = COPY $rc6
    ; CHECK-NEXT: CmpBrZero %bb.2, undef $z, 1, $rc6, implicit-def $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: liveins: $y, $rs2, $rs3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: DEY_Implied
    ; CHECK-NEXT: $a = LDIndirIdx $rs3, $y
    ; CHECK-NEXT: STIndirIdx $a, $rs2, $y
    ; CHECK-NEXT: TYA_Implied implicit-def $z
    ; CHECK-NEXT: BR %bb.1, $z, 0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: RTS
    MemMoveReverse $rs2, $rs3, $rc6, $rc7, implicit-def $a, implicit-def $x, implicit-def $y, implicit-def $c, implicit-def $n, implicit-def $v, implicit-def $z
    RTS
...
