; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s | FileCheck %s

; Test memory operations with variable sizes that use Y-indexed loops.
; memcpy and memset use reverse loops (DEY/BPL) for efficiency.
; memmove uses forward loops to preserve correct semantics for overlapping regions.

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos"

; Test memcpy with variable size - uses reverse Y-indexed loop with TYA/BNE
define void @test_memcpy(i8* %dst, i8* %src, i8 %size) {
; CHECK-LABEL: test_memcpy:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc6
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx __rc7
; CHECK-NEXT:    ldy __rc6
; CHECK-NEXT:    beq .LBB0_2
; CHECK-NEXT:  .LBB0_1: ; %entry
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    dey
; CHECK-NEXT:    lda (__rc4),y
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    tya
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  .LBB0_2: ; %entry
; CHECK-NEXT:    rts
entry:
  %size16 = zext i8 %size to i16
  call void @llvm.memcpy.p0i8.p0i8.i16(i8* %dst, i8* %src, i16 %size16, i1 false)
  ret void
}

; Test memset with variable size - uses reverse Y-indexed loop with TYA/BNE
define void @test_memset(i8* %dst, i8 %val, i8 %size) {
; CHECK-LABEL: test_memset:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    stx __rc4
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx __rc5
; CHECK-NEXT:    ldy __rc4
; CHECK-NEXT:    beq .LBB1_2
; CHECK-NEXT:  .LBB1_1: ; %entry
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    tya
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  .LBB1_2: ; %entry
; CHECK-NEXT:    rts
entry:
  %size16 = zext i8 %size to i16
  call void @llvm.memset.p0i8.i16(i8* %dst, i8 %val, i16 %size16, i1 false)
  ret void
}

; Test memmove with variable size - uses forward loop to handle overlapping correctly
define void @test_memmove(i8* %dst, i8* %src, i8 %size) {
; CHECK-LABEL: test_memmove:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc6
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx __rc7
; CHECK-NEXT:    ldy #0
; CHECK-NEXT:  .LBB2_1: ; %entry
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lda (__rc4),y
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    iny
; CHECK-NEXT:    cpy __rc6
; CHECK-NEXT:    bne .LBB2_1
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    rts
entry:
  %size16 = zext i8 %size to i16
  call void @llvm.memmove.p0i8.p0i8.i16(i8* %dst, i8* %src, i16 %size16, i1 false)
  ret void
}

; Test small inline memset (should be inlined, not use loop)
define void @test_memset_inline(i8* %dst) {
; CHECK-LABEL: test_memset_inline:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    tay
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    iny
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    iny
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    iny
; CHECK-NEXT:    sta (__rc2),y
; CHECK-NEXT:    rts
entry:
  call void @llvm.memset.p0i8.i16(i8* %dst, i8 0, i16 4, i1 false)
  ret void
}

; Test overlapping memmove with known dst > src (reverse copy needed)
; When dst is higher than src and they overlap, must copy backwards
; Note: Currently uses indirect indexed addressing; absolute indexed is a future optimization
@overlap_buf = internal global [64 x i8] zeroinitializer
define void @test_memmove_overlap_dst_gt_src() {
; CHECK-LABEL: test_memmove_overlap_dst_gt_src:
; CHECK:       ; %bb.0: ; %entry
; CHECK:         ldy __rc2
; CHECK-NEXT:    beq .LBB{{[0-9]+}}_2
; CHECK-NEXT:  .LBB{{[0-9]+}}_1:
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    dey
; CHECK-NEXT:    lda (__rc6),y
; CHECK-NEXT:    sta (__rc4),y
; CHECK-NEXT:    tya
; CHECK-NEXT:    bne .LBB{{[0-9]+}}_1
; CHECK-NEXT:  .LBB{{[0-9]+}}_2:
; CHECK-NEXT:    rts
entry:
  ; Copy 32 bytes from buf[0] to buf[16] - overlapping, dst > src
  %dst = getelementptr [64 x i8], [64 x i8]* @overlap_buf, i16 0, i16 16
  %src = getelementptr [64 x i8], [64 x i8]* @overlap_buf, i16 0, i16 0
  call void @llvm.memmove.p0i8.p0i8.i16(i8* %dst, i8* %src, i16 32, i1 false)
  ret void
}

; Test overlapping memmove with known dst < src (forward copy is safe)
; When dst is lower than src, forward copy is correct
; Note: Currently uses indirect indexed addressing; absolute indexed is a future optimization
define void @test_memmove_overlap_dst_lt_src() {
; CHECK-LABEL: test_memmove_overlap_dst_lt_src:
; CHECK:       ; %bb.0: ; %entry
; CHECK:         ldy #0
; CHECK-NEXT:  .LBB{{[0-9]+}}_1:
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lda (__rc4),y
; CHECK-NEXT:    sta (__rc6),y
; CHECK-NEXT:    iny
; CHECK-NEXT:    cpy __rc2
; CHECK-NEXT:    bne .LBB{{[0-9]+}}_1
; CHECK-NEXT:  ; %bb.{{[0-9]+}}:
; CHECK-NEXT:    rts
entry:
  ; Copy 32 bytes from buf[16] to buf[0] - overlapping, dst < src
  %dst = getelementptr [64 x i8], [64 x i8]* @overlap_buf, i16 0, i16 0
  %src = getelementptr [64 x i8], [64 x i8]* @overlap_buf, i16 0, i16 16
  call void @llvm.memmove.p0i8.p0i8.i16(i8* %dst, i8* %src, i16 32, i1 false)
  ret void
}

declare void @llvm.memcpy.p0i8.p0i8.i16(i8*, i8*, i16, i1)
declare void @llvm.memset.p0i8.i16(i8*, i8, i16, i1)
declare void @llvm.memmove.p0i8.p0i8.i16(i8*, i8*, i16, i1)
