name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare a cmake environment
      run: |
        mkdir -p build/stage1
        cd build/stage1
        cmake ../../llvm
        cmake --build . --target install --config Release
